version: "3.8"

volumes:
  postgres_data: {}

services:
  django:
    container_name: boiler-django
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app/
    ports:
      - 8001:8001
    depends_on:
      - postgres
    env_file:
      - ./docker/.env
    stdin_open: true
    tty: true

  postgres:
    container_name: boiler-postgres
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./docker/.env
