version: '3.8'

volumes:
    postgres_data: {}

services:
    django:
        container_name: trees-django
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - postgres
        env_file:
            - ./docker/.env
        stdin_open: true
        tty: true

    postgres:
        container_name: trees-postgres
        image: postgres:latest
        restart: on-failure
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./docker/.env
