# Generated by Django 3.2.5 on 2021-07-25 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=63)),
                ('slug', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=63)),
                ('is_first', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_steps', to='trees.solution')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=63)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('steps', models.ManyToManyField(blank=True, related_name='paths', to='trees.Step')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=63)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceding_options', to='trees.step')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='trees.step')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=63)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paths', models.ManyToManyField(blank=True, related_name='trees', to='trees.Path')),
            ],
            options={
                'unique_together': {('name', 'creator')},
            },
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.CheckConstraint(check=models.Q(('is_first', False), ('is_final', False), _connector='OR'), name='not_first_and_final'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_final', False), ('solution__isnull', True)), models.Q(('is_final', True), ('solution__isnull', False)), _connector='OR'), name='not_final_with_no_solution'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.CheckConstraint(check=models.Q(('step', django.db.models.expressions.F('next_step')), _negated=True), name='steps_not_equal'),
        ),
    ]
