name: Github Actions

on: [push]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    env:
      ENGINE: django.db.backends.postgresql
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: server.config.settings
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-in-project: false
          virtualenvs-create: false

      - name: Load cached Poetry venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

      - name: Test with pytest
        run: poetry run pytest
